# Generated by Django 5.0.7 on 2024-07-17 20:00

import album.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Album Name')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Album Description')),
                ('album_picture', models.ImageField(default='photos/album_photos/default/default_album_pic.png', upload_to=album.models.define_album_photos_directory, verbose_name='Profile Picture')),
                ('is_private', models.BooleanField(default=False, verbose_name='Is Album Private?')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
    ]
