# Generated by Django 5.0.7 on 2024-07-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Album Description'),
        ),
    ]
