# Generated by Django 5.0.7 on 2024-07-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='new_email',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_discoverable',
            field=models.BooleanField(default=False, verbose_name='Is Account Discoverable?'),
        ),
    ]
