# Generated by Django 5.0.7 on 2024-07-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_remove_useraccount_new_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='is_discoverable',
            field=models.BooleanField(default=True, verbose_name='Is Account Discoverable?'),
        ),
    ]
