# Generated by Django 5.0.7 on 2024-07-16 20:53

import user_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_alter_useraccount_is_discoverable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_picture',
            field=models.ImageField(default='photos/account_photos/default/default_profile_pic.svg', upload_to=user_account.models.define_account_photos_directory, verbose_name='Profile Picture'),
        ),
    ]
