# Generated by Django 5.0.7 on 2024-07-17 20:00

import user_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_alter_useraccount_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_picture',
            field=models.ImageField(default='photos/account_photos/default/default_profile_pic.png', upload_to=user_account.models.define_account_photos_directory, verbose_name='Profile Picture'),
        ),
    ]
