# Generated by Django 5.0.7 on 2024-07-22 18:02

import data_and_caption.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album', '0002_alter_album_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAndCaption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Title')),
                ('file', models.FileField(blank=True, null=True, upload_to=data_and_caption.models.define_files_directory, verbose_name='Saved File')),
                ('url', models.CharField(blank=True, max_length=250, null=True, verbose_name='Saved URL')),
                ('owner_description', models.CharField(blank=True, max_length=500, null=True, verbose_name="Owner's Description")),
                ('ai_based_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='AI Based Description')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='album.album', verbose_name='Album')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'File and Caption',
                'verbose_name_plural': 'Files and Captions',
            },
        ),
    ]
