# Generated by Django 5.0.7 on 2024-07-22 18:19

import data_and_caption.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_and_caption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataandcaption',
            name='ai_based_description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='AI-based Description'),
        ),
        migrations.AlterField(
            model_name='dataandcaption',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=data_and_caption.models.define_files_directory, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='dataandcaption',
            name='owner_description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name="Owner's Description"),
        ),
        migrations.AlterField(
            model_name='dataandcaption',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='URL'),
        ),
    ]
